name: Main Workflow

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context (to check variables)
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"
          echo "PR source branch: ${{ github.event.pull_request.head.ref }}"
          
      - name: Trigger Build Workflow via API
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
          -d '{"ref":"refs/heads/${{ github.event.pull_request.head.ref }}"}'

  wait_for_build_completion:
    needs: trigger_build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Build Workflow to complete
        run: |
          build_status="in_progress"
          while [ "$build_status" != "completed" ]; do
            echo "Waiting for build workflow to complete..."
            # Check the status of the build workflow
            build_status=$(curl -s \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs \
              | jq -r ".workflow_runs[] | select(.head_sha == \"${{ github.sha }}\") | .status")
            sleep 10  # Check every 10 seconds
          done
          echo "Build workflow completed with status: $build_status"
          # Optionally check the conclusion (success or failure)
          build_conclusion=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs \
            | jq -r ".workflow_runs[] | select(.head_sha == \"${{ github.sha }}\") | .conclusion")
          if [ "$build_conclusion" != "success" ]; then
            echo "Build workflow failed, aborting the automerge process."
            exit 1
          fi
          
  trigger_automerge:
    needs: trigger_build  # This ensures the next job runs only after the previous one completes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Automerge Workflow using GitHub API
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/automerge.yml/dispatches \
          -d '{
                "ref": "refs/heads/${{ github.event.pull_request.head.ref }}", 
                "inputs": {
                  "pr_number": "${{ github.event.pull_request.number }}"
                }
              }'
