name: Main Workflow

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context (to check variables)
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"
          echo "PR source branch: ${{ github.event.pull_request.head.ref }}"
          
      - name: Trigger Build Workflow via API
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
          -d '{"ref":"refs/heads/${{ github.ref }}"}'

  trigger_automerge:
    needs: trigger_build  # This ensures the next job runs only after the previous one completes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Automerge Workflow using GitHub API
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/automerge.yml/dispatches \
          -d '{"ref":"refs/heads/${{ github.ref }}"}'
